# Generated by Django 5.1.15 on 2026-08-21 11:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.URLField(help_text='Cover Image URL', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('photography_type', models.CharField(max_length=100)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('contacted', 'Contacted Client'), ('booked', 'Session Booked'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('email_notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=255)),
                ('price', models.CharField(help_text='e.g. ₹35,000', max_length=50)),
                ('numeric_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_popular', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(max_length=100)),
                ('edited_photos', models.CharField(max_length=100)),
                ('deliverables', models.JSONField(default=list)),
                ('accent_color', models.CharField(default='#2563EB', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'numeric_price'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('event_date', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quote', models.TextField()),
                ('client_avatar', models.URLField(max_length=500)),
                ('featured_photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cloudinary_public_id', models.CharField(blank=True, help_text='Cloudinary asset ID or key', max_length=255)),
                ('image_url', models.URLField(help_text='High-resolution image URL', max_length=500)),
                ('aspect_ratio', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape'), ('square', 'Square')], default='portrait', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('year', models.CharField(default='2026', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='studio_api.category')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('starting_price', models.CharField(help_text='e.g. ₹45,000', max_length=50)),
                ('numeric_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image_url', models.URLField(max_length=500)),
                ('icon_name', models.CharField(default='Sparkles', max_length=50)),
                ('features', models.JSONField(default=list, help_text='List of bullet points')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio_api.category')),
            ],
        ),
    ]
